### ISSUE TITLE
Yard documentation

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#101]
Implement Yard documentation.
- [x] Page on YC site. 
- [x] Grammar language description
- [x] Examples
- [x] Comparison with other languages (ANTLR, Yacc ...)

**Comment by ArsenShnurkov** [comment]
Какое нафиг "ready" ? 
"Implement Yard documentation."
задача провалена!

Сценарии использования описаны? Нет! Трансляция use-case в тербования сделана? нет!
Требования выписаны? Нет! Трекинг требований до реализации в коде организован? нет!
Документация содержит туториалы типа walkthrough? а как насчёт описания архитектуры кода? Откройте ГОСТ 19, посмотрите что должно быть в документации...

Есть абсолютно непролинкованная свалка документов, которая даже не в HTML-формате...

**Comment by gsvgit** [comment]
Здравствуйте.

Мы очень рады, что Вы обратили внимание на наш проект.

Ваши замечания обязательно будут учтены.

Спасибо.

Regards,
Semyon Grigorev.

8 сентября 2015 г., 21:31 пользователь ArsenShnurkov <
notifications@github.com> написал:
