### ISSUE TITLE
Symbolic Finite Transducers for string-embedded language lexing

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#102]
- [x] Read article ["Equivalence of Finite-Valued Symbolic Finite Transducers"](http://www.easychair.org/smart-program/PSI2015/2015-08-26.html#talk:10349)
- [ ] Use [this implementation](https://github.com/AutomataDotNet/Automata) of Symbolic Finite Transducers for string-embedded language lexing
  - [x] FL course
    - [x] Compare FST composition performance with basic implementation and optimized version (issue #63)
  - [ ]  Course work
     - [ ] Is it possible to optimize Microsoft.Automata?
     - [ ] Evaluate lexing performance
     - [ ] ? Replace custom FST and FSA with implemented in [Automata](https://github.com/AutomataDotNet/Automata) project

**Comment by kajigor** [comment]
You can request the paper from me

**Comment by gsvgit** [comment]
@GuminEgor   project we had discussed: https://github.com/AutomataDotNet/Automata

**Comment by gsvgit** [comment]
Related repos
*  https://github.com/GuminEgor/YaccConstructor
* https://github.com/GuminEgor/Automata
