### ISSUE TITLE
No example of parsing EBNF-grammar (ISO style) with YaccConstructor

### ISSUE THREAD

**Issue by ArsenShnurkov** [YaccConstructor/YaccConstructor#104]
Implement EBNF-ISO frontend. Details below.

Does it understand  ISO/IEC 14977 : 1996(E) - http://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf  syntax for grammar files?

Here
http://yaccconstructor.github.io/YaccConstructor/yard.html
it is said that it can (i.e. header and footer of YARD syntax is optional, and the rest is looks like EBNF).

But there are some moments of EBNF like special sequences, which should be documented better.

Specifically, i want to compile this grammar - 
https://raw.githubusercontent.com/ArsenShnurkov/mono-packaging-tools/ff639ffab880e86b90b456c30fbd543861a96de4/mpt-gitmodules/bnf3/syntax3.ebnf

And I need an example of how to use generated AST tree which will be build after parse of sample file with my grammar.

**Comment by gsvgit** [comment]
* [Example](https://github.com/YaccConstructor/Examples/blob/master/EBNF_104/EBNF_104/EbnfIso.yrd)
* [Documentation](http://yaccconstructor.github.io/YaccConstructor/yard.html)

**Comment by ArsenShnurkov** [comment]
Thanks.
