### ISSUE TITLE
Change build config to not build each commit

### ISSUE THREAD

**Issue by adamralph** [YaccConstructor/YaccConstructor#13]
Today, 40 commits went into the dev branch, which queued 40 builds on codebetter CI, which have so far occupied both Jetbrains agents for about 6 hours, with about 1 hour to go.

For the future, would it be possible to change the build config so that each commit is not built separately? E.g. this would have reduced the build agent utilisation today from about 7 hours to about 10 minutes.

**Comment by raymon-02** [comment]
Thanks for this comment. I have changed the VCS trigger parameters for all configurations

**Comment by adamralph** [comment]
Great - thank you very much!

**Comment by gsvgit** [comment]
Does problem solved? Could issue be closed?

**Comment by adamralph** [comment]
It seems like the build config is now set to build multiple commits so yes, this can be closed.

Thanks for making the changes.
