### ISSUE TITLE
Git push problem

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#14]
http://teamcity.codebetter.com/viewLog.html?tab=buildLog&buildTypeId=YaccConstructor_YcCoreGeneralBuild&buildId=186323#_state=453&focus=14045

fatal: unable to access 'https://YcGeneralUser:*******@/': Failed connect to :443; No error

Seems that it is url for google repo.

Why CI configurations are so unstable?

**Comment by raymon-02** [comment]
There were reference to repo in scripts. I fexed it: all such references are variables in configurations now.
Fixed all configurations
