### ISSUE TITLE
YC.SDK.Runtime Mono issue

### ISSUE THREAD

**Issue by likeanowl** [YaccConstructor/YaccConstructor#197]
Mono issue:

Adding YC.SDK.Runtime...
Attempting to resolve dependency 'FSharp.Core (≥ 4.3.0)'.
Unable to resolve dependency 'FSharp.Core (≥ 4.3.0)'.

**Comment by gsvgit** [comment]
@likeanowl Try to use new version (0.1.0-beta2)

**Comment by likeanowl** [comment]
@gsvgit Successfully installed 'YC.SDK.Runtime 0.1.0.0-beta2'. Fine, thanks.
