### ISSUE TITLE
Add command-line parameter for disabling bindings with yrd files in generated parser file 

### ISSUE THREAD

**Issue by darthorimar** [YaccConstructor/YaccConstructor#204]
Now, when compiling yrd files using YaccConstructor, it's also generates bindings with generated fs file. VS redirects all compilation errors to source yrd files. But it does not work correctly, e.g., it may show error on empty line. So, it would be great to have an option to disable this behavior.

**Comment by gsvgit** [comment]
Added in 0.1.0.1. Try it out. Just add "-bindSrc=false" to args of generator.
