### ISSUE TITLE
Graph-string alignment with graph parsing

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#214]
Source is graph (metagenomic assembly). Template is a string. String can be compressed to grammar: [sequitur](https://en.m.wikipedia.org/wiki/Sequitur_algorithm), [parallel squitur](http://ieeexplore.ieee.org/document/7345625/?reload=true) LZ78 or LZW. This grammar can be "relaxed" in order to deal with mismatches and deletion/insertion. After that graph parsing algorithm can be applied for graph-string alignment.

- [ ] Find or implement one of compression algorithm. Grammar representation is YARD IL.
- [ ] Implement grammar "relaxation".
- [ ] Modify GLL in order to deal with "relaxed" weighed grammar.
- [ ] Evaluate on metagenomic assemblies and 16s sequences.

- [Online demo](http://www.sequitur.info/)
- [Useful presentation about sequitur](https://courses.cs.washington.edu/courses/csep590a/07au/lectures/lecture05small.pdf)
- [Compressed Pattern Matching for Sequitur](http://www.shino.ecei.tohoku.ac.jp/~ayumi/papers/DCC2001sequitur.pdf)
- [Collage system: a unifying framework for compressed pattern matching](http://www.sciencedirect.com/science/article/pii/S0304397502004267)

**Comment by gsvgit** [comment]
@Albert1401
First part.
- [x] Fork -> Clone -> build YaccConstructor. Branch: GLL-FSA
- [x] Try to create grammar for 16s sequences (YaccConstructor\Tests\data\bio\16s\ ) by using sequitur online demo. Select one or two sequences.
- [x] Create converter from sequitur grammar to yard grammar. 
- [ ] Try to parse selected sequences wrt created grammar by using GLL. Examples of parsing with GLL: YaccConstructor\Tests\GLLParser.Simple.Tests\GLLParserSimpleTest.fs

**Comment by Albert1401** [comment]
- [x]  Fork -> Clone -> build YaccConstructor. Branch: GLL-FSA
- [x] Try
 to create grammar for 16s sequences (YaccConstructor\Tests\data\bio\16s\ ) by using sequitur online demo. Select one or two sequences.
- [x]  Create converter from sequitur grammar to yard grammar.
- [x] Try to parse selected sequences wrt created grammar by using GLL. Examples of parsing with GLL: YaccConstructor\Tests\GLLParser.Simple.Tests\GLLParserSimpleTest.fs

**Comment by Albert1401** [comment]
- [x] Create converter from sequitur grammar to yard grammar.
 - [x] Try to parse selected sequences wrt created grammar by using GLL. Examples of parsing with GLL: YaccConstructor\Tests\GLLParser.Simple.Tests\GLLParserSimpleTest.fs

**Comment by Albert1401** [comment]
Здравствуйте
Правильно ли я понимаю, что достаточно для исходных правил выставить вес равный 0, а для правил которыми мы добавляем ошибки != 0.
И при достижении какого-то заданного лимита прекращать рассматривать этот вариант разбора?

**Comment by gsvgit** [comment]
Достаточно для чего? 
Не знаю, для чего, но лучше немного иначе.
1) Подавать на вход токен error только если наче из данной позиции никак не сдвинуться
2) Хранить в дескрипторе кол-во переходов по error токенам. Если это кол-во превосходит некоторый лимит, то не продолжать обработку данного дескриптора.
