### ISSUE TITLE
Sequitur implementation

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#220]
Implement  [sequitur](https://en.m.wikipedia.org/wiki/Sequitur_algorithm) string compression algorithm in F#.
- [ ] Unicode support
- [x] Implement result splitting by special symbols. For example, I compress string ```s1$s2%s3``` where $ and % are special characters which are not in ```s1```, ```s2``` or ```s3```. After compression sequitur returns rule of form ```n -> w1$w2%w3```. It should be converted in rule with alternatives: ```n -> w1 | w2 | w3```.
- [x] Final grammar representation is [YARD IL](https://github.com/YaccConstructor/YaccConstructor/blob/dev/src/Common/IL.fs)
- [x] Tests
- [x] Evaluate on 16s sequences

Useful links.
- [Online demo](http://www.sequitur.info/)
- [Useful presentation about sequitur](https://courses.cs.washington.edu/courses/csep590a/07au/lectures/lecture05small.pdf)

**Comment by ZinovyevaAnna** [comment]
беру вот эту

**Comment by gsvgit** [comment]
Unicode support is unnecessary.
