### ISSUE TITLE
Свободные от решений(*.sln) проекты(*.?proj)

### ISSUE THREAD

**Issue by MallabaevAzamat** [YaccConstructor/YaccConstructor#225]
Свободные проекты -- те, на которые есть ссылки из других проектов, но не объявлены в решении

В YC на 11 марта 2017 таким является по-крайней мере один проект: AbstractAnalysis.Common

Свободные проекты не могут быть использованы xbuild

Для создания сборки под моно необходимо:
- либо выделить свободные проекты в отдельное решение и собирать как отдельную цель, а затем использовать ссылки на готовые библиотеки
- либо добавить свободные проекты в существующее решение

Решение данной проблемы необходимо для подготовки сборки под linux/mono #224

**Comment by gsvgit** [comment]
AbstractAnalysis.Common точно можно добавить во все решения, в которых он нужен.

**Comment by MallabaevAzamat** [comment]
Сделал со всеми подобными проектами в #224
