### ISSUE TITLE
Report on linear input processing with 16s grammar.

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#238]
- [x] Prepare full size genomes with annotated 16s positions.
- [x] Report ([here](https://github.com/YaccConstructor/articles/tree/master/InProgress/16s_grammar_report))
  - [x] Parsing of 16s sequences. All should be parsed. If we use partial grammar (for middle part), then positions should be checked.
  - [x] Full size genomes parsing. Full statistical quality estimation: precision, recall, false positive, ets. Metrics should be selected.

Grammar may be tuned. Current version tuned for one of our metagenomic assembly, so can be less generic then required.

**Comment by dm-kovalev** [comment]
Handwriting grammar isn't good enough for bio-hunting
