### ISSUE TITLE
Mono.addins can't find any addin after rebuild

### ISSUE THREAD

**Issue by gorohovart** [YaccConstructor/YaccConstructor#242]
Also, mono build fails instantly(not only after rebuild).

I have refactored main YaccConstructor project and this have led to such issue. But I have no idea why.

**Comment by gsvgit** [comment]
@likeanowl and @MallabaevAzamat should kill Mono.Addins. So... I think that it is not a problem)

**Comment by gorohovart** [comment]
hurray

**Comment by svitkovsergey** [comment]
I'll have a whole summer for this... (or maybe not)

**Comment by likeanowl** [comment]
#239 related to this

**Comment by svitkovsergey** [comment]
Rewrite this files in .fsx without using YC.YaccConstructor.exe
- [ ] src/Bio.Search/gen.cmd
- [ ] src/Bio.Search/gen.sh
- [x] src/GLL.Parser.Test/gen.cmd
- [x] src/YardFrontend/gen.sh
- [x] tests/ControlFlowGraph.Tests/gen.cmd
- [x] tests/GLL.AbstractParser.Simple.Tests/gen.cmd
- [x] tests/GLL.AbstractParser.Simple.Tests/gen.sh
- [ ] tests/GLL.AbstractParser.Simple.Tests/genBio.cmd
- [ ] tests/GLL.AbstractParser.Simple.Tests/genGraph.cmd
- [ ] tests/GLL.AbstractParser.Simple.Tests/genOLD.cmd
- [ ] tests/GLL.AbstractParser.Simple.Tests/gen_bio.cmd
- [ ] tests/GLL.AbstractParser.Simple.Tests/gen_graph.cmd
- [x] tests/GLLParser.Simple.Tests/gen.cmd
- [x] tests/GLLParser.Simple.Tests/gen.sh
- [ ] tests/GLLParser.Simple.Tests/genDBG.cmd
- [x] tests/GLLParser.Simple.Tests/genSimpleCalc.cmd
- [x] tests/GLLParser.Simple.Tests/genSimpleCalc.sh:mono
- [x] tests/RIGLRParser.SimpleTest/gen.cmd
- [x] tests/RIGLRParser.SimpleTest/gen.sh
- [x] tests/RNGLRAbstractParser.Tests/gen.cmd
- [x] tests/RNGLRAbstractParser.Tests/gen.sh
- [x] tests/RNGLRParser.Simple.Tests/gen.cmd
- [x] tests/RNGLRParser.Simple.Tests/gen.sh

**Comment by svitkovsergey** [comment]
Seems pretty fixed with #246

**Comment by gsvgit** [comment]
Yes, but mono build should be fixed first.

**Comment by svitkovsergey** [comment]
Does current version allows to make release?

**Comment by gsvgit** [comment]
@likeanowl Problem with fsi execution on mono fixed, but some gen scripts looks broken (https://travis-ci.org/YaccConstructor/YaccConstructor/builds/240286445) Fix it.
