### ISSUE TITLE
Тестовая задача

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#268]
Написать эссе (2-3 страницы 12 шрифтом) на тему "Решения задачи ХХХ через операции над матрицами", где ХХХ -- любая задача на ваш выбор.

Ссылки на текст (предпочтительный формат -- pdf) оставлять в комментариях к этой таске. Вопросы задавать там же.

**Comment by alexander-bzikadze** [comment]
Здравствуйте.

Любая задача - любая задача из предложенных для [CSC](https://github.com/YaccConstructor/YaccConstructor/labels/CSC) или же любая задача вообще?

С уважением,
Александр

**Comment by gsvgit** [comment]
@alexander-bzikadze любая задача вообще.

**Comment by devcrocod** [comment]
https://drive.google.com/open?id=0B-p3L7SqIgGgY1B6ZmphZ29hLWs

**Comment by katyacyfra** [comment]
Здравствуйте!
https://drive.google.com/file/d/0B6v2UPNb_jHCRnN4Q3VmNHN0V28/view

С уважением,
Екатерина

**Comment by alexander-bzikadze** [comment]
Здравствуйте.
[Задачка](https://github.com/YaccConstructor/YaccConstructor/files/1309289/sle_for_n.3.32.pdf)

С уважением,
Александр

**Comment by natalymr** [comment]
Здравствуйте!

https://drive.google.com/file/d/0BwlB_D4WGVgtR1NrcFBteDBEX0k/view

С уважением,
Наталья

**Comment by natalymr** [comment]
Здравствуйте!

https://drive.google.com/file/d/0BwlB_D4WGVgtOUhkTU9oWGxCTU0/view

С уважением,
Наталья

**Comment by dvolkow** [comment]
Здравствуйте!
[решение](https://yadi.sk/i/D6qD15AG3My9Ai)

С уважением, Волков Д.В.

**Comment by acanna** [comment]
Здравствуйте!
[document.pdf](https://github.com/YaccConstructor/YaccConstructor/files/1309975/document.pdf)


С уважением,
Аня Цалапова
