### ISSUE TITLE
Conjunctive path querying implementation and evaluation

### ISSUE THREAD

**Issue by rustam-azimov** [YaccConstructor/YaccConstructor#279]
There is a [paper 1](https://github.com/YaccConstructor/articles/tree/master/InProgress/Conjunctive_Path_Querying) with conjunctive path querying algorithm (In progress, without evaluation).
There is a [paper 2](https://dl.acm.org/citation.cfm?id=3009848) with linear conjunctive path querying algorithm. 

- [x] Extract dataset and conjunctive grammars from the evaluation of paper 2
- [x] Implement algorithm from paper 1 in YaccConstructor and test it on the extracted dataset

**Comment by gsvgit** [comment]
Implemented and evaluated.
Grammars which appear in static code analysis are huge, so naive matrix-based algorithm is a bad choice: performance is very bad.
