### ISSUE TITLE
Test. Быстрое умножение булевых матриц (GPGPU)

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#324]
Для "Быстрое умножение булевых матриц" (версия на GPGPU, #321)

Реализовать на OpenCL C или Cuda C максимально производительное вычисление поэлементного "и" для битовых матриц.

Результат: ссылка на репозиторий с решением в комментариях к этому issue.

**Comment by eaniconer** [comment]
https://github.com/eaniconer/csc/tree/master/practices/JetBrainsResearch/BitwiseProductOfBinaryMatrices
