### ISSUE TITLE
Test. Графовые базы данных: алгоритмы поиска путей

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#326]
Для тех, кто хочет заниматься одной из этих задач: #342, #106 или #306.

Известно, что пересечение произвольного контекстно-свободного языка с произвольным регулярным -- это некоторый контекстно-свободный язык. Предложите алгоритм, который по контекстно-свободной граммтике и конечному автомату строит результат пересечения соответствующих языков в виде конекстно-свободной грамматики. Какова пространственная и временная сложность предложенного алгоритма? Почему?

Результат: ссылка на pdf-документ с описанием алгоритма и оценками в комментариях к этому issue. Дополнительно можно прикрепить ссылку на реализацию предложенного алгоритма.

**Comment by misha-nik** [comment]
[Test.pdf](https://github.com/YaccConstructor/YaccConstructor/files/3607131/Test.pdf)
Слегка смущает просьба отправить решение через коментарий к issue. Надеюсь, что я все сделал правильно)
