### ISSUE TITLE
Test. Вывод типов для Ruby-библиотек

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#327]
Для "Вывод типов для Ruby-библиотек" (#322 )

- Реализуйте абстрактное синтаксическое дерево для языка, в котором есть переменные, элементарная арифметика, сравнения, процедуры (и возможность их вызывать, соответственно), условные ветвления.
- Реализуйте построение графа вызовов но бстрактному синтаксическому дереву.
- Реализуйте поиск (взаимно)рекурсивных вызовов по графу вызовов.

Результат: ссылка на репозиторий с решением в комментариях к этому issue.

**Comment by GoPavel** [comment]
https://github.com/GoPavel/syntax-tree

**Comment by AlexVanGogen** [comment]
Добрый вечер!
Ссылка на репозиторий: https://github.com/AlexVanGogen/recursions-analyzer

С уважением,
Александр Кузнецов.
