### ISSUE TITLE
Test. Матрицы на GPGPU

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#343]
Для тех, кто хочет заниматься [этой задчей](https://github.com/SokolovYaroslav/CFPQ-on-GPGPU/issues/30)

Реализовать на CUDA C максимально производительное решение для поэлементного "and" битовых матриц. 

Результат: ссылка на репозиторий с реализацией в комменатриях к этой задаче.

**Comment by akhoroshev** [comment]
@gsvgit 
Добрый вечер!

У меня не было под рукой видеокарты nvidia, поэтому написал на OpenCL для встроенной графики intel hd620.

https://github.com/akhoroshev/simple_opencl_example

В репозитории код, который применяет побитовое И к двум массивам. В качестве метрики оценивающей производительность, я выбрал memory bandwidth. Так как подсистема памяти в моем случае использует RAM, то максимально возможный bandwidth по [заявлению](https://ark.intel.com/content/www/ru/ru/ark/products/95443/intel-core-i5-7200u-processor-3m-cache-up-to-3-10-ghz.html) Intel в двухканальном режиме на моем процессоре порядка 34 GB/s. У меня вышло 15Gb/s, возможно, у меня одноканальный режим памяти, либо можно было сделать в два раза быстрее :)
