### ISSUE TITLE
YC Web

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#6]
Web UI for YC. Web-demo.
Technology: WebSharper
- Algorithms visualization
- Algorithms description
- Algorithms comparison
- Predefined examples
- Interactivity
  - Grammars changing/specification
  - Input specification

- [x] Unify and move to one single repo with name YC.Web
   - Recursive autmata visualization. Input: grammar from editor or file, output: RA
   - #174 
   - #175
   - [YC.BioGraph](https://github.com/YaccConstructor/YC.BioGraph)
   - [YC.GraphParsingDemo](https://github.com/YaccConstructor/YC.GraphParsingDemo)
   - [YC.Bio.Web](https://github.com/YaccConstructor/YC.Bio.Web) 

- [x] Remove osolete repos.
- [ ] Integration with Appharbor or other hosting service.

**Comment by ShalamovRoman** [comment]
Я взял эту задачу.

**Comment by gsvgit** [comment]
@ShalamovRoman Вы перенесли код из всех трёх репозиториев в основной? Их можно удалять?

**Comment by gsvgit** [comment]
Hosting is new separated task: https://github.com/YaccConstructor/YC.Web/issues/6
