### ISSUE TITLE
Integration with FsLexYacc

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#79]
Investigate possibility of integration with [FsLexYacc](http://fsprojects.github.io/FsLexYacc) for creation general language processing platform in F# and for F#.

**Comment by MallabaevAzamat** [comment]
Заметка, по опыту FSharp.PowerPack  (#199):
При использовании FsLexYacc можно задействовать кастомные таски
Но так можно получить не собирающийся под linux билд, потому что в unix учитывается регистр файлов (в этом имя файла fslex.exe/fsyacc.exe может отличаться от использованного в таске)

**Comment by gsvgit** [comment]
Хм... А можно совсем отказаться от кастомных тасок? Не нравятся мне они) Ну
да, поменять имена файликов всё равно придётся.

Regards,
Semyon Grigorev.

11 марта 2017 г., 22:54 пользователь Mallabaev Azamat (Fenex9428) <
notifications@github.com> написал:

**Comment by gsvgit** [comment]
Obsolete.
