### ISSUE TITLE
Full DOT parser

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#91]
- [ ] Implement full DOT language parser with YC/Yard  in GrammarZOO.
- [ ] Implement left- and right-recursive EBNF conversion and switch for it. s -> a* could be transformed to s -> EPS | a s or to s -> EPS | s a. One of this case already implemented.
       - [ ] Evaluate on DOT parser

**Comment by auduchinok** [comment]
Conversion.fs (for second task)

**Comment by auduchinok** [comment]
Fix for parsing is in QuickGraph repo.
https://github.com/YaccConstructor/QuickGraph/pull/17
