### ISSUE TITLE
LR0 -> LALR1 table transformation visualization

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#96]
Visualize tables transformation during LR0 -> LALR(1) transition. Use Fasio tables.

**Comment by gsvgit** [comment]
Visualize tables transformation during LR0 -> LALR(1) transition. Use Fasio tables.

**Comment by KokovDanil** [comment]
Как я понимаю, нужно сделать визуализацию трансформации LR0 -> LALR(1) с помощью fasio tables? (прикрутить facio к LR0 -> LALR(1)?)

**Comment by gsvgit** [comment]
Да, нужна визуализация. Прикручивать ничего не надо, у него уже есть эти таблицы и трансформации. Надо разобраться с их представлением и сделать визуализацию

**Comment by KokovDanil** [comment]
А что подразумевается под визуализацией? Какой-то понятный вывод этих таблиц?

**Comment by gsvgit** [comment]
Сами таблицы должны быть представлены в виде, используемом в классическом изложении LR анализа: Action и GOTO таблицы, с состояниями и символами. При этом должна быть очевидна связь с грамматикой. Видимо, хочется одновременно видеть грамматику, LR(0), LR(1) и LALR(1) таблицы. Как-то аккуратно разложенные, чтобы было понятно, что изменилось при переходе от одних к другим.

**Comment by KokovDanil** [comment]
Спасибо
