### ISSUE TITLE
Grammar type provider

### ISSUE THREAD

**Issue by gsvgit** [YaccConstructor/YaccConstructor#97]
How to
- http://blog.mavnn.co.uk/type-providers-from-the-ground-up/
- https://github.com/fsprojects/FSharp.TypeProviders.StarterPack
- Scannerless GLL
- Exclude generation step. 

Expected result:
```
type P = GLL("s : s s | s s s | A")
let sppf = P.Parse("AAA")
```

**Comment by Columpio** [comment]
Will assign for this

**Comment by gsvgit** [comment]
Just use GrammarCombinators
